// Generated by CoffeeScript 1.4.0
(function() {
  var app, config, express, rjs;

  express = require('express');

  rjs = require('rjs').installPrototypes();

  config = require('./config').config;

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: config.sessionSecret
  }));

  app.use(express["static"](__dirname + '/public'));

  require('./controllers/index.js')(app);

  app.listen(process.env.PORT, function() {
    return console.log('Listening on port ' + process.env.PORT);
  });

  exports.app = app;

}).call(this);
