// Generated by CoffeeScript 1.4.0
(function() {
  var app, config, express, render, rjs;

  express = require('express');

  rjs = require('rjs').installPrototypes();

  config = require('./config').config;

  render = require('./controller-helper.js').render;

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: config.sessionSecret
  }));

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return render(req, res, {
      title: 'Project Name',
      seed: {
        view: 'index'
      }
    });
  });

  app.get('/:page', function(req, res) {
    return render(req, res, {
      title: 'Project Name',
      seed: {
        view: req.params.page
      }
    });
  });

  app.listen(process.env.PORT, function() {
    return console.log('Listening on port ' + process.env.PORT);
  });

  exports.app = app;

}).call(this);
