// Generated by CoffeeScript 1.4.0
(function() {
  var NodestrapGenerator, path, util, yeoman;

  util = require("util");

  path = require("path");

  yeoman = require("yeoman-generator");

  NodestrapGenerator = module.exports = function NodestrapGenerator(args, options, config) {
    yeoman.generators.Base.apply(this, arguments);
    this.on("end", function() {
      return this.installDependencies({
        skipInstall: options["skip-install"]
      });
    });
    return this.pkg = JSON.parse(this.readFileAsString(path.join(__dirname, "../package.json")));
  };

  util.inherits(NodestrapGenerator, yeoman.generators.NamedBase);

  NodestrapGenerator.prototype.askFor = function askFor() {
    var cb, prompts;
    cb = this.async();
    prompts = [
      {
        name: "spa",
        message: "Generate a single page application?",
        "default": "Y/n"
      }
    ];
    return this.prompt(prompts, function(err, props) {
      if (err) {
        return this.emit("error", err);
      }
      this.spa = /y/i.test(props.spa);
      return cb();
    }).bind(this);
  };

  NodestrapGenerator.prototype.app = function app() {
    this.copy("_package.json", "package.json");
    this.copy("_component.json", "component.json");
    this.copy("Gruntfile.coffee", "Gruntfile.coffee");
    return this.copy("Procfile", "Procfile");
  };

  NodestrapGenerator.prototype.views = function views() {
    var layoutType;
    layoutType = this.spa ? 'spa' : 'default';
    return this.copy("views/layout-" + layoutType + ".jade", "views/layout.jade");
  };

}).call(this);
